language: cpp
install:
  - sudo add-apt-repository main
  - sudo add-apt-repository universe
  - sudo add-apt-repository restricted
  - sudo add-apt-repository multiverse
  - sudo apt-get update
  - sudo apt-get install nuget
  - nuget restore vs/aldente.sln
script:
  - make